# Generated by Django 4.0.1 on 2022-07-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='Film',
        ),
    ]
